name: RAcount
channels:
  - defaults
  - conda-forge
  - chembl
dependencies:
  - pip=20.0.2
  - python=3.6.10
  - django=2.2.5
  - cython=0.29.15
  - rdkit=2019.09.3
  - chembl_structure_pipeline=1.0.0
  - bokeh=2.1.1
  - pip:
    - django-cors-headers==3.1.1
    - djangorestframework==3.11.0
    - argon2-cffi==19.2.0
    - pytablereader
    - pytablewriter
    - django-debug-toolbar==2.2
    - django-choices
