# Generated by Django 2.0.2 on 2019-04-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('inputs', models.TextField()),
                ('inputs_comments', models.TextField()),
                ('outputs', models.TextField()),
                ('outputs_comments', models.TextField()),
                ('node_seq', models.IntegerField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.IntegerField()),
                ('resources_name', models.CharField(max_length=255)),
                ('resources_link', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('nickName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Users'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Projects'),
        ),
    ]
