# Generated by Django 2.2.5 on 2019-10-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

def initialize_users(apps, schema_editor):
    User = get_user_model()
    user = User.objects.create_user('manuel.pastor@upf.edu', first_name='Manuel', last_name='Pastor', email='manuel.pastor@upf.edu', password='Manuel')
    user.save()
    user = User.objects.create_user('***REMOVED***', first_name='Ignacio', last_name='Pasamontes Fúnez', email='***REMOVED***', password='Ignacio')
    user.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_users),
        migrations.AlterField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
