# Generated by Django 2.2.5 on 2019-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20191014_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='inputs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='inputs_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='outputs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='outputs_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
