# Generated by Django 2.2.5 on 2019-12-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20191118_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_filename', models.CharField(max_length=80, unique=True)),
                ('filename', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update_by', models.IntegerField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=520, null=True)),
                ('url', models.CharField(blank=True, max_length=520, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('is_molecule', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDescriptionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Projects'),
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Projects')),
            ],
        ),
    ]
