# Generated by Django 2.2.5 on 2019-12-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20191209_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AddField(
            model_name='file',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Nodes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
