# Generated by Django 2.2.5 on 2019-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20191218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.CharField(blank=True, max_length=520, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=520, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='commentfile',
            constraint=models.UniqueConstraint(fields=('project', 'file'), name='unique_project_file'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(fields=('name', 'extension'), name='unique_name_extension'),
        ),
        migrations.AddConstraint(
            model_name='nodes',
            constraint=models.UniqueConstraint(fields=('project', 'node_seq'), name='unique_project_node_seq'),
        ),
        migrations.AddConstraint(
            model_name='problemdescriptionfile',
            constraint=models.UniqueConstraint(fields=('project', 'file'), name='problem_unique_project_file'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.UniqueConstraint(fields=('node', 'resources_name'), name='unique_node_resources_name'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.UniqueConstraint(fields=('node', 'resources_link'), name='unique_node_resources_link'),
        ),
    ]
