# Generated by Django 2.2.5 on 2020-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20191218_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_filename',
            field=models.CharField(max_length=80),
        ),
    ]
