# Generated by Django 2.2.5 on 2020-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20200217_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='name',
            field=models.CharField(blank=True, default='Unnamed', max_length=255),
        ),
    ]
