# Generated by Django 2.2 on 2020-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200217_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetype',
            name='history_node_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
