# Generated by Django 2.2 on 2020-05-06 21:33

import API.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20200506_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='int_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compound',
            name='cas',
            field=models.CharField(max_length=12, null=True, validators=[API.validators.CASRNValidator()]),
        ),
    ]
