# Generated by Django 2.2 on 2020-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20200506_2133'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compound',
            constraint=models.UniqueConstraint(fields=('project', 'int_id'), name='unique_project_int_id'),
        ),
    ]
