# Generated by Django 2.2 on 2020-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_compound_ra_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='ra_type',
            field=models.IntegerField(choices=[(0, 'Target compound'), (1, 'Source compound')]),
        ),
    ]
