# Generated by Django 2.2 on 2020-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20200507_1332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compound',
            name='unique_project_int_id',
        ),
        migrations.AddConstraint(
            model_name='compound',
            constraint=models.UniqueConstraint(fields=('project', 'ra_type', 'int_id'), name='unique_project_ra_type_int_id'),
        ),
    ]
