# Generated by Django 2.2 on 2020-05-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20200507_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='cas',
            new_name='cas_rn',
        ),
    ]
