# Generated by Django 2.2 on 2020-06-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20200608_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamatrixfields',
            name='std_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datamatrixstdunit', to='API.Unit'),
        ),
        migrations.AlterField(
            model_name='datamatrixfields',
            name='std_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datamatrixfields',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datamatrixunit', to='API.Unit'),
        ),
        migrations.AlterField(
            model_name='datamatrixfields',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
