# Generated by Django 2.2 on 2020-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_datamatrixfields_assay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamatrixfields',
            name='text_value',
            field=models.TextField(default=None, null=True),
        ),
    ]
