# Generated by Django 2.2 on 2020-08-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_datamatrixfields_text_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.TextField(null=True, unique=True),
        ),
    ]
