# Generated by Django 2.2 on 2020-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_auto_20200826_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='chembl_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
