# Generated by Django 2.2 on 2020-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_compound_chembl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamatrixfields',
            name='assay_type',
            field=models.IntegerField(choices=[(0, 'Calculated physicochemical properties'), (1, 'Biological activity'), (2, 'Physicochemical assay')], default=1),
        ),
    ]
