# Generated by Django 2.2 on 2020-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_datamatrixfields_assay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamatrixfields',
            name='assay_type',
            field=models.IntegerField(choices=[(0, 'Predictect physicochemical properties'), (1, 'Biological activity'), (2, 'Physicochemical assay')]),
        ),
    ]
