# Generated by Django 2.2 on 2021-01-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_auto_20210118_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialraxhypothesis',
            old_name='quatitative_var_approach',
            new_name='quantitative_var_approach',
        ),
    ]
