# Generated by Django 2.2.5 on 2021-01-29 05:54

import API.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20210119_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCASRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_rn', models.CharField(max_length=12, null=True, validators=[API.validators.CASRNValidator()])),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Compound')),
            ],
        ),
    ]
