# Generated by Django 2.2.5 on 2021-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_compoundcasrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='cas_rn',
        ),
    ]
