# Generated by Django 2.2.5 on 2021-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_remove_compound_cas_rn'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compoundcasrn',
            constraint=models.UniqueConstraint(fields=('compound', 'cas_rn'), name='unique_compound_casrn'),
        ),
    ]
