# Generated by Django 2.2.5 on 2021-02-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_auto_20210210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundcasrn',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_rn', to='API.Compound'),
        ),
    ]
