# Generated by Django 2.2.5 on 2021-02-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_auto_20210210_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Compound')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Projects', unique=True)),
            ],
        ),
    ]
