# Generated by Django 2.2.5 on 2021-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0039_tcompound'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compound',
            constraint=models.UniqueConstraint(fields=('project', 'chembl_id'), name='unique_project_chembl_id'),
        ),
    ]
