# Generated by Django 2.2.5 on 2021-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_auto_20210305_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='tanimoto',
            field=models.FloatField(default=1.0),
        ),
    ]
