# Generated by Django 2.0.2 on 2019-04-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAcount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='instrument',
        ),
    ]
